server.forward-headers-strategy: framework
server.servlet.session.cookie.secure: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.jdbc.time_zone: UTC
spring.jpa.show-sql: false
logging.level.org.springframework.security: INFO
